### ISSUE TITLE
02_01_1DConvection: round-off

### ISSUE THREAD

**Issue by bknaepen** [numerical-mooc/numerical-mooc#127]
The third python cell of the above notebook reads:
-----
u = numpy.ones(nx)      #numpy function ones()
u[.5/dx : 1/dx+1]=2  #setting u = 2 between 0.5 and 1 as per our I.C.s
print(u)
-----

Is it safe to assume that .5/dx and 1/dx + 1 will always convert to the intended integer values? Isn't it better to call the round function to make sure as in?

-----
u = numpy.ones(nx)      #numpy function ones()
start = round(.5/dx)
end = round(1/dx)
u[start : end +1] = 2  #setting u = 2 between 0.5 and 1 as per our I.C.s
print(u)
-----

Cheers,
Bernard.

**Comment by labarba** [comment]
I do have to agree that your suggestion makes for more readable code. As to whether integer division or using `round()` is best, I think they are equally valid implementation decisions.
