### ISSUE TITLE
Module 1 coding assignment (Rocket flight) issue

### ISSUE THREAD

**Issue by mghadam** [numerical-mooc/numerical-mooc#174]
Hello,

I have developed the code for the assignment. I think there are several parts that are ambiguous: 
1- It is not clear from the figure that what is the propellant burn rate at t=5. Is it 20 or 0?
2- When using Euler method, f(u) has to be evaluated at t=n (and not t=n+1 or n+1/2).Is it right?
3- Using the dt=0.1 of the assignment, there is no discrete point with h=0 to find when the rocket impacted the ground. Shall I use linear interpolation to find associated time and velocity of h=0 point?

I got the following results by assuming mdot=20 at t=5 and evaluate f(u) at t=n 
```
Vmax is: 237.2
t @ Vmax is: 5.1
h @ Vmax is: 546.73
hmax is: 1372.04
t @ hmax is: 15.9
```
but the system doesn't approve them. 

Thanks

**Comment by gforsyth** [comment]
Hey @mghadam 

1. The figure is ambiguous, it's true.  But if you calculate how much fuel you are burning and you start with 100kg of propellant, then you'll see that mdot = 0 at t = 5
2. Yes
3. We assigned a dt = 0.1 so you can stick with that level of precision throughout.  That is, if at 5.1 seconds, the rocket has a positive altitude and at 5.2 seconds it has a negative altitude, you can take 5.2 seconds to be the time of impact.

**Comment by mghadam** [comment]
Please can you confirm if the above results of v,h & t are right? The problem is that the edX system doesn't accept them.

**Comment by gforsyth** [comment]
No, they're all slightly off because you're burning for one extra timestep.

**Comment by mghadam** [comment]
Here are the first parts of my solution array:
```
0    0.0    0.0
1    0.0    3.35233333333
2    0.335233333333    6.76273723787
...

I think the edX answers are calculated by evaluating mdot and mp at t=n+1/2 instead of t=n.

**Comment by gforsyth** [comment]
Hey @mghadam, those are correct for the first few timesteps.  If you change your burn time you should get the right answers.  
The edX answers are calculated using t=n

**Comment by mghadam** [comment]
Ok fixed.

At least, I found that edX is accepting the maximum velocity in a range between 233.00 to 233.70. This is why I thought they were calculated at t=n+1/2.

**Comment by gforsyth** [comment]
There is some wiggle room in the grader, but not a whole lot

**Comment by mghadam** [comment]
@gforsyth thank you

**Comment by gforsyth** [comment]
Happy to help!  If you have other questions you can open an issue, or join the gitter room at gitter.im

If you post in the forum on the edx platform you can also use LaTeX-like math typesetting (if needed), but do ping us somewhere else to let us know you have a question since the forum doesn't send notifications.

**Comment by nightwolfer1** [comment]
I can't get the correct answer for the impact part. I found the indices for the position where height is below zero, and then took it out from my time array. The result was 28.20 for the time of impact. Using same indices for the velocity I got -470.77 (470.80 in the grader). Anyone with similar problem?

**Comment by labarba** [comment]
Hi @nightwolfer1 — We don't provide homework help on this site. You also won't find other learners using the material answering questions here. You can try your luck in the discussion board in the online course platform.

**Comment by nightwolfer1** [comment]
labarba thanks for the fast reply i will try my luck there instead.
