### ISSUE TITLE
Reword section on SymPy root finding in Module 3 Lesson 3

### ISSUE THREAD

**Issue by gforsyth** [numerical-mooc/numerical-mooc#192]
It seems that the roots are returned in a non-deterministic order -- either this is a machine-by-machine thing or has to do with recent changes before SymPy 1.0.

Not a huge deal, but to avoid confusion, we should rewrite that section a bit and then automatically choose the positive root.

**Comment by ncclementi** [comment]
I've just created a pull request fixing this, take a look at it and if you agree merge it.

**Comment by gforsyth** [comment]
Closed via  	8e1d14f
